[project]
name = "string_grouper"
version = "0.7.2"
description = "String grouper contains functions to do string matching using TF-IDF and the cossine similarity."
authors = [
    {name = "Chris van den Berg"},
    {name = "ParticularMiner"},
    {name = "Vincent Chalmel"},
]

maintainers = [
    {name = "Chris van den Berg"},
    {name = "Guillaume Pressiat"},
    {name = "Vincent Chalmel"},
]

license = "MIT"
readme = "README.md"

packages = [
    { include = "string_grouper" },
    { include = "string_grouper_utils" },
]

requires-python = "<4.0,>=3.10"

dependencies = [
    "pandas<3.0,>=2.0",
    "scipy>=1.15",
    "scikit-learn>=1.4.0",
    "numpy>=2.0",
    "sparse-dot-topn>=1.1.0",
    "loguru>0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"